FROM python:3.12-slim

# Install git
RUN apt-get update && apt-get install -y git

# Prepare ComfyUI source code and install useful tools
WORKDIR /ComfyUI
COPY . .
RUN pip install --upgrade pip && pip install -r requirements.txt && pip install comfy-cli
RUN cd /ComfyUI/custom_nodes && git clone https://github.com/ltdrdata/ComfyUI-Manager.git
